name: clipboad_image
description: "A Flutter plugin to get image from clipboard."
version: 0.0.1
homepage:

license: MIT

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.aqsa.clipboad_image
        pluginClass: ClipboadImagePlugin
      ios:
        pluginClass: ClipboadImagePlugin

